### ISSUE TITLE
Wrong body padding when there is no navbar

### ISSUE THREAD

**Issue by andreassolberg** [andreassolberg/uninett-bootstrap-theme#4]
In the uninett css, there is a fixed top padding for body:

``` css
body {
    background-color:#eeebe8;
    font-family: 'colfaxRegular', Arial, sans-serif;
    font-size: 16px;
    line-height: 1.6;
    padding-top: 70px;
}
```

This padding is correct with the one-line fixed navbar, but it fails when the navbar height is changed from the default. And it also fails when the navbar is not present. The navbar should not be a required component of a web page.
