### ISSUE TITLE
Always show scrollbar to better align navbar

### ISSUE THREAD

**Issue by andreassolberg** [andreassolberg/uninett-bootstrap-theme#5]
When scrollbar shows and dissappears the navbar jumps. To always show scrollbar, try the following

``` css
html {
    overflow-y: scroll;
}
```
